# This stage is responsible for holding onto
# your config without copying it directly into
# the final image
FROM scratch AS stage-files
COPY ./files /files

# Copy modules
# The default modules are inside blue-build/modules
# Custom modules overwrite defaults
FROM scratch AS stage-modules
COPY ./modules /modules

# Bins to install
# These are basic tools that are added to all images.
# Generally used for the build process. We use a multi
# stage process so that adding the bins into the image
# can be added to the ostree commits.
FROM scratch AS stage-bins
COPY --from=ghcr.io/sigstore/cosign/cosign:v2.6.1 /ko-app/cosign /bins/cosign
COPY --from=ghcr.io/blue-build/cli:latest-installer \
  /out/bluebuild /bins/bluebuild
# Keys for pre-verified images
# Used to copy the keys into the final image
# and perform an ostree commit.
#
# Currently only holds the current image's
# public key.
FROM scratch AS stage-keys
COPY cosign.pub /keys/leblue.pub


# Main image
FROM ghcr.io/ublue-os/aurora-dx@sha256:9246e7386d78c79a2bc50d59206b3febf3455aae40a8275c684cff347c0a5d56 AS leblue
ARG RECIPE=recipes/recipe.yml
ARG IMAGE_REGISTRY=localhost
ARG BB_BUILD_FEATURES=""
ARG CONFIG_DIRECTORY="/tmp/files"
ARG MODULE_DIRECTORY="/tmp/modules"
ARG IMAGE_NAME="leblue"
ARG BASE_IMAGE="ghcr.io/ublue-os/aurora-dx"
ARG FORCE_COLOR=1
ARG CLICOLOR_FORCE=1
ARG RUST_LOG_STYLE=always
# Key RUN
RUN --mount=type=bind,from=stage-keys,src=/keys,dst=/tmp/keys \
  mkdir -p /etc/pki/containers/ \
  && cp /tmp/keys/* /etc/pki/containers/

# Bin RUN
RUN --mount=type=bind,from=stage-bins,src=/bins,dst=/tmp/bins \
  mkdir -p /usr/bin/ \
  && cp /tmp/bins/* /usr/bin/
RUN --mount=type=bind,from=ghcr.io/blue-build/nushell-image:default,src=/nu,dst=/tmp/nu \
  mkdir -p /usr/libexec/bluebuild/nu \
  && cp -r /tmp/nu/* /usr/libexec/bluebuild/nu/
RUN \
--mount=type=bind,src=.bluebuild-scripts_a3cd3a07,dst=/scripts/,Z \
  /scripts/pre_build.sh

# Module RUNs
RUN \
--mount=type=bind,from=stage-files,src=/files,dst=/tmp/files,rw \
--mount=type=bind,from=ghcr.io/blue-build/modules/files:latest,src=/modules,dst=/tmp/modules,rw \
--mount=type=bind,src=.bluebuild-scripts_a3cd3a07,dst=/tmp/scripts/,Z \
  --mount=type=cache,dst=/var/cache/rpm-ostree,id=rpm-ostree-cache-leblue-42,sharing=locked \
  --mount=type=cache,dst=/var/cache/libdnf5,id=dnf-cache-leblue-42,sharing=locked \
/tmp/scripts/run_module.sh 'files' '{"type":"files","files":[{"source":"system","destination":"/"}]}'
RUN \
--mount=type=bind,from=stage-files,src=/files,dst=/tmp/files,rw \
--mount=type=bind,from=ghcr.io/blue-build/modules/rpm-ostree:latest,src=/modules,dst=/tmp/modules,rw \
--mount=type=bind,src=.bluebuild-scripts_a3cd3a07,dst=/tmp/scripts/,Z \
  --mount=type=cache,dst=/var/cache/rpm-ostree,id=rpm-ostree-cache-leblue-42,sharing=locked \
  --mount=type=cache,dst=/var/cache/libdnf5,id=dnf-cache-leblue-42,sharing=locked \
/tmp/scripts/run_module.sh 'rpm-ostree' '{"type":"rpm-ostree","install":["blueman"],"remove":["sddm-breeze","sddm-wayland-plasma","plasma-lookandfeel-fedora","plasma-print-manager-libs","plasma-print-manager","plasma-desktop","plasma-workspace","kwin"]}'
RUN \
--mount=type=bind,from=stage-files,src=/files,dst=/tmp/files,rw \
--mount=type=bind,from=ghcr.io/blue-build/modules/rpm-ostree:latest,src=/modules,dst=/tmp/modules,rw \
--mount=type=bind,src=.bluebuild-scripts_a3cd3a07,dst=/tmp/scripts/,Z \
  --mount=type=cache,dst=/var/cache/rpm-ostree,id=rpm-ostree-cache-leblue-42,sharing=locked \
  --mount=type=cache,dst=/var/cache/libdnf5,id=dnf-cache-leblue-42,sharing=locked \
/tmp/scripts/run_module.sh 'rpm-ostree' '{"type":"rpm-ostree","install":["kwallet","pam-kwallet","qt5-qtgraphicaleffects","qt5-qtquickcontrols2","qt5-qtsvg","sddm","sddm-themes"]}'
RUN \
--mount=type=bind,from=stage-files,src=/files,dst=/tmp/files,rw \
--mount=type=bind,from=ghcr.io/blue-build/modules/systemd:latest,src=/modules,dst=/tmp/modules,rw \
--mount=type=bind,src=.bluebuild-scripts_a3cd3a07,dst=/tmp/scripts/,Z \
  --mount=type=cache,dst=/var/cache/rpm-ostree,id=rpm-ostree-cache-leblue-42,sharing=locked \
  --mount=type=cache,dst=/var/cache/libdnf5,id=dnf-cache-leblue-42,sharing=locked \
/tmp/scripts/run_module.sh 'systemd' '{"type":"systemd","system":{"enabled":["sddm-boot.service"]}}'
RUN \
--mount=type=bind,from=stage-files,src=/files,dst=/tmp/files,rw \
--mount=type=bind,from=ghcr.io/blue-build/modules/rpm-ostree:latest,src=/modules,dst=/tmp/modules,rw \
--mount=type=bind,src=.bluebuild-scripts_a3cd3a07,dst=/tmp/scripts/,Z \
  --mount=type=cache,dst=/var/cache/rpm-ostree,id=rpm-ostree-cache-leblue-42,sharing=locked \
  --mount=type=cache,dst=/var/cache/libdnf5,id=dnf-cache-leblue-42,sharing=locked \
/tmp/scripts/run_module.sh 'rpm-ostree' '{"type":"rpm-ostree","repos":["https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo"],"install":["fuzzel","hyprland","hyprlock","hypridle","hyprpaper","hyprshot","hyprsunset","swww","waybar","xdg-desktop-portal-hyprland"]}'
RUN \
--mount=type=bind,from=stage-files,src=/files,dst=/tmp/files,rw \
--mount=type=bind,from=ghcr.io/blue-build/modules/default-flatpaks:latest,src=/modules,dst=/tmp/modules,rw \
--mount=type=bind,src=.bluebuild-scripts_a3cd3a07,dst=/tmp/scripts/,Z \
  --mount=type=cache,dst=/var/cache/rpm-ostree,id=rpm-ostree-cache-leblue-42,sharing=locked \
  --mount=type=cache,dst=/var/cache/libdnf5,id=dnf-cache-leblue-42,sharing=locked \
/tmp/scripts/run_module.sh 'default-flatpaks' '{"type":"default-flatpaks","configurations":[{"scope":"system","install":["io.github.getnf.embellish","org.virt_manager.virt-manager"]}]}'
RUN \
--mount=type=bind,from=stage-files,src=/files,dst=/tmp/files,rw \
--mount=type=bind,from=ghcr.io/blue-build/modules/rpm-ostree:latest,src=/modules,dst=/tmp/modules,rw \
--mount=type=bind,src=.bluebuild-scripts_a3cd3a07,dst=/tmp/scripts/,Z \
  --mount=type=cache,dst=/var/cache/rpm-ostree,id=rpm-ostree-cache-leblue-42,sharing=locked \
  --mount=type=cache,dst=/var/cache/libdnf5,id=dnf-cache-leblue-42,sharing=locked \
/tmp/scripts/run_module.sh 'rpm-ostree' '{"type":"rpm-ostree","install":["emacs","git","zsh"]}'
RUN \
--mount=type=bind,from=stage-files,src=/files,dst=/tmp/files,rw \
--mount=type=bind,from=ghcr.io/blue-build/modules/signing:latest,src=/modules,dst=/tmp/modules,rw \
--mount=type=bind,src=.bluebuild-scripts_a3cd3a07,dst=/tmp/scripts/,Z \
  --mount=type=cache,dst=/var/cache/rpm-ostree,id=rpm-ostree-cache-leblue-42,sharing=locked \
  --mount=type=cache,dst=/var/cache/libdnf5,id=dnf-cache-leblue-42,sharing=locked \
/tmp/scripts/run_module.sh 'signing' '{"type":"signing"}'

RUN \
--mount=type=bind,src=.bluebuild-scripts_a3cd3a07,dst=/scripts/,Z \
  /scripts/post_build.sh

# Labels are added last since they cause cache misses with buildah
LABEL org.blue-build.build-id="5daef71f-2995-44b1-9b9e-3328268a40e0"
LABEL org.opencontainers.image.title="leblue"
LABEL org.opencontainers.image.description="This is my personal OS image."
LABEL org.opencontainers.image.source=""
LABEL org.opencontainers.image.base.digest="sha256:9246e7386d78c79a2bc50d59206b3febf3455aae40a8275c684cff347c0a5d56"
LABEL org.opencontainers.image.base.name="ghcr.io/ublue-os/aurora-dx:42"
LABEL org.opencontainers.image.created="2025-10-12T20:10:47.735720237+00:00"
LABEL io.artifacthub.package.readme-url=https://raw.githubusercontent.com/blue-build/cli/main/README.md